pdf_data_dir = "/esat/izar/dgrujici/IntegrationData/dirs_PDF"
image_data_dir = "/esat/izar/dgrujici/IntegrationData/dirs_PPM"
trees_data_dir = "/esat/izar/dgrujici/IntegrationData/dirs_TREE"
html_data_dir = "/esat/izar/dgrujici/IntegrationData/dirs_HTML"
natural_images_dir = "/esat/izar/dgrujici/IntegrationData/natural_images"
figures_dir = "/esat/izar/dgrujici/IntegrationData/figures"
